### ISSUE TITLE
build instructions for ubuntu 18.04

### ISSUE THREAD

**Issue by ariedederde** [opinkerfi/winexe-waf#12]
Hi,

I was able to build this winexe fork on ubuntu 18.04. I have not tested the build thoroughly, but up until now all tests have succeeded. Use at your own risk.

1.
```
apt-get install gcc pkg-config liblmdb-dev liblmdb0 lmdb-utils \
  libgnutls28-dev libgnutlsxx28 libgpgme11-dev libarchive-dev \
  libacl1-dev libldap2-dev gcc-mingw-w64 comerr-dev libpopt-dev \
  libbsd-dev zlib1g-dev libc6-dev python-dev
```
2.
```
git clone https://github.com/BitDesert/winexe.git winexe
cd winexe
git clone git://git.samba.org/samba.git samba
git checkout a6bda1f2bc85779feb9680bc74821da5ccd401c5
```
3.
in samba/buildtools/wafsamba/samba_perl.py:59
change (comment out)
  `perl_inc.remove('.')`
to
  `#perl_inc.remove('.')`

4.
in samba/source4/lib/tls/tls.c:601
change (comment out)
  `gnutls_certificate_type_set_priority(tls->session, cert_type_priority);`
to
  `// gnutls_certificate_type_set_priority(tls->session, cert_type_priority);`

5.
in samba/source4/lib/tls/tls_tstream.c:1017
change (comment out)
  `gnutls_certificate_type_set_priority(tlss->tls_session,cert_type_priority);`
to
  `// gnutls_certificate_type_set_priority(tlss->tls_session,cert_type_priority);`

6.
in source/debug.h
change

```
extern int lcl_debug_level;

#define CHECK_DEBUGLVL( level ) \
  ( ((level) <= MAX_DEBUG_LEVEL) && \
    unlikely(lcl_debug_level >= (level)))

#define DEBUG( level, body ) \
  (void)( ((level) <= MAX_DEBUG_LEVEL) && \
    unlikely(lcl_debug_level >= (level))           \
      && (dbgtext body) )

#define DEBUGLVL( level ) \ 
  ( CHECK_DEBUGLVL(level) )

int dbgtext( const char *, ... );
```

into
```
extern int lcl_debug_level;

#ifndef CHECK_DEBUGLVL
#define CHECK_DEBUGLVL( level ) \
  ( ((level) <= MAX_DEBUG_LEVEL) && \
    unlikely(lcl_debug_level >= (level)))
#endif

#ifndef DEBUG
#define DEBUG( level, body ) \
 (void)( ((level) <= MAX_DEBUG_LEVEL) && \
   unlikely(lcl_debug_level >= (level))           \
    && (dbgtext body) )
#endif

#ifndef DEBUGLVL
#define DEBUGLVL( level ) \
  ( CHECK_DEBUGLVL(level) )
#endif

// int dbgtext( const char *, ... );
bool dbgtext( const char *, ... );
```

7.
in source/debug.c
change (comment out)
```
int dbgtext(const char *format, ...)
{
  va_list args;
  va_start(args,format);
  vprintf(format,args);
  va_end(args);
  return 0;
};
```
into
```
/***
int dbgtext(const char *format, ...)
{
  va_list args;
  va_start(args,format);
  vprintf(format,args);
  va_end(args);
  return 0;
};
****/
```

8.
```
# my host has 4 cpu's, hence -j4
cd source
./waf --samba-dir=../samba  -j4 configure
./waf --samba-dir=../samba  -j4 build
```

**Comment by r0cketm4n** [comment]
`tlscert.c:(.text+0x1134): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x1174): undefined reference to `gnutls_x509_crt_set_serial'
tlscert.c:(.text+0x11d2): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x120d): undefined reference to `gnutls_x509_crt_set_activation_time'
tlscert.c:(.text+0x126b): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x12a6): undefined reference to `gnutls_x509_crt_set_expiration_time'
tlscert.c:(.text+0x1304): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x133a): undefined reference to `gnutls_x509_crt_set_ca_status'
tlscert.c:(.text+0x1398): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x13d5): undefined reference to `gnutls_x509_crt_set_key_purpose_oid'
tlscert.c:(.text+0x1433): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x1469): undefined reference to `gnutls_x509_crt_set_version'
tlscert.c:(.text+0x14c7): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x150b): undefined reference to `gnutls_x509_crt_get_key_id'
tlscert.c:(.text+0x1569): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x15ab): undefined reference to `gnutls_x509_crt_set_subject_key_id'
tlscert.c:(.text+0x1609): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x164b): undefined reference to `gnutls_x509_crt_sign'
tlscert.c:(.text+0x16a9): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x1747): undefined reference to `gnutls_x509_crt_export'
tlscert.c:(.text+0x17a5): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x187f): undefined reference to `gnutls_x509_crt_export'
tlscert.c:(.text+0x18dd): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x19b7): undefined reference to `gnutls_x509_privkey_export'
tlscert.c:(.text+0x1a15): undefined reference to `gnutls_strerror'
tlscert.c:(.text+0x1ad3): undefined reference to `gnutls_x509_privkey_deinit'
tlscert.c:(.text+0x1ae2): undefined reference to `gnutls_x509_privkey_deinit'
tlscert.c:(.text+0x1af1): undefined reference to `gnutls_x509_crt_deinit'
tlscert.c:(.text+0x1b00): undefined reference to `gnutls_x509_crt_deinit'
tlscert.c:(.text+0x1b05): undefined reference to `gnutls_global_deinit'
collect2: error: ld returned 1 exit status
`

I did all those changes, the configure runs fine but these errors appear when running the build

**Comment by mariosoliman** [comment]
I ran into the same issue and found this fix https://github.com/opinkerfi/winexe-waf/issues/5#issuecomment-225540437 which worked

Note that it will compile build/winexe-static, which you can copy to /usr/bin and rename to just winexe

**Comment by gardart** [comment]
https://github.com/opinkerfi/winexe-waf/commit/4b0a69c16dc2a60f323d7fda89aa9582bb71089d
