### ISSUE TITLE
Access problem on 2012 R2

### ISSUE THREAD

**Issue by mgomila** [opinkerfi/winexe-waf#6]
Hello, 

I need your help to fix my problem. 
I suppose that some "client" changes on his OS (windows server 2012 R2) have blocked my "winexe" acces, but i can't determine what's is wrong.

This is my debug log. Is like "get version" command return nothing in infinite loop.
Any idea ?

> Got NTLMSSP neg_flags=0x60088215
>   NTLMSSP_NEGOTIATE_UNICODE
>   NTLMSSP_REQUEST_TARGET
>   NTLMSSP_NEGOTIATE_SIGN
>   NTLMSSP_NEGOTIATE_NTLM
>   NTLMSSP_NEGOTIATE_ALWAYS_SIGN
>   NTLMSSP_NEGOTIATE_NTLM2
>   NTLMSSP_NEGOTIATE_128
>   NTLMSSP_NEGOTIATE_KEY_EXCH
> IN: async_open(\ahexec, 2)
> IN: async_open_recv
> CTRL: Sending command: get version
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> CTRL: Unknown command:
> CTRL: Received:
> .........
> ........
> .....

**Comment by gardart** [comment]
have you checked out if UAC (user account control) or some GPO is getting in the way ?
